server:
  port: ${PORT:8080}
  shutdown: graceful
spring:
  application:
    name: eligibility-api
  lifecycle:
    timeout-per-shutdown-phase: 20s
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
app:
  observability:
    service: ${DD_SERVICE:eligibility-api}
    environment: ${DD_ENV:local}
    version: ${DD_VERSION:local}
logging:
  level:
    root: INFO
    com.example.observability: INFO
